#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import json
import datetime


def get_time():
    """
    Generate a formatted timestamp for currenttime
    """
    return str(datetime.datetime.now())


def get_autogen_header(path=None):
    file_path = os.path.join(path, "list_raw.txt")

    with open(file_path, "r") as f:
        data_version = f.readlines()[2]
        data_version = data_version[2:]
        data_version = data_version.rstrip()
        data_version = data_version.split('=')[-1]

        f.close()

    # Autogenerated header
    autogen_header = "This file was generated by The-Big-Username-Blacklist %s (at %s)" % (  # NOQA
        data_version, get_time()
    )

    return autogen_header


def convert(path=None):
    """
    Loads data from list_raw and generates files in the following formats:
        - newline
        - json
        - python
        - js (ES5)
        - js (ES6)
        - php

    """
    # Load raw
    file_path = os.path.join(path, "list_raw.txt")

    with open(file_path, "r") as f:
        raw_usernames = f.readlines()

        # Remote newline
        usernames = [x.strip("\n") for x in raw_usernames]

        # Remove trailing #
        usernames = [x for x in usernames if x and not x.startswith("#")]

        # Sort list
        usernames.sort()

        f.close()

    # Write optimized newline file
    file_path = os.path.join(path, "list.txt")

    optimized_data = "".join("%s\n" % e for e in usernames)
    optimized_data = optimized_data.strip()

    autogen_header = get_autogen_header(path=path)

    with open(file_path, "w") as f:
        f.write(optimized_data)
        f.close()

    # Write optimized json file
    file_path = os.path.join(path, "list.json")

    with open(file_path, "w") as f:
        json.dump(usernames, f, indent=4, ensure_ascii=False)
        f.close()

    # Write python file
    file_path = os.path.join(path, "list.py")

    with open(file_path, "w") as f:
        f.write("# %s\n" % autogen_header)
        f.write("data = %s" % str(usernames))
        f.close()

    # Write es6 module
    file_path = os.path.join(path, "list.js")

    with open(file_path, "w") as f:
        f.write("// %s\n" % autogen_header)
        f.write("export default %s;" % str(usernames))
        f.close()

    # Write commonjs module
    file_path = os.path.join(path, "list-commonjs.js")

    with open(file_path, "w") as f:
        f.write("// %s\n" % autogen_header)
        f.write("module.exports = %s;" % str(usernames))
        f.close()

    # write PHP file
    file_path = os.path.join(path, "list.php")

    with open(file_path, "w") as f:
        f.write("<?php \n")
        f.write("// %s\n" % autogen_header)
        f.write("return %s;" % str(usernames))
        f.close()


if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.realpath(__file__))
    list_dir = os.path.join(current_dir, os.pardir)

    convert(path=list_dir)
